auto: true
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json" , "README.md"]
timezone: JPN
sass:
  sass_dir: ./_sass/
  style: compressed
name: MyJekyllSite
encoding: utf-8
author: asdfghj
